// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFH_aHv2I6S-dWntYhSaW2Td897MgCxVY',
    appId: '1:640385027934:android:6e89533d2877afa2d749cf',
    messagingSenderId: '640385027934',
    projectId: 'dengue-e5553',
    databaseURL: 'https://dengue-e5553-default-rtdb.firebaseio.com',
    storageBucket: 'dengue-e5553.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXiMDAkpNQl3_dN9WaR7IDzvqA0tK_JVc',
    appId: '1:640385027934:ios:0693da9657cca42ad749cf',
    messagingSenderId: '640385027934',
    projectId: 'dengue-e5553',
    databaseURL: 'https://dengue-e5553-default-rtdb.firebaseio.com',
    storageBucket: 'dengue-e5553.firebasestorage.app',
    iosClientId: '640385027934-qr3g2tfn103ofttvig306250mv7tg1cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.dengueZero',
  );
}
